FROM python:3.12-slim

ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY requirements-consumer.txt .
RUN pip install --no-cache-dir -r requirements-consumer.txt

COPY ./src/aura_consumer ./src/aura_consumer

CMD ["python", "-m", "src.aura_consumer.main"]
